### ISSUE TITLE
Adding loot containers to converted configs.

### ISSUE THREAD

**Issue by RebornOG** [EvgenyN-Lowner/Custom-Keycards#1]
How do we add loot containers to converted configs. ? Ive set doors with object builder and are using these from the old version. Can we add loot containers to these configs ?

**Comment by EvgenyN-Lowner** [comment]
yes, you have `"LootCrates": []` in your converted config. add in this array your new loot crates. You can see how its done in new [default config](https://github.com/EvgenyN-Lowner/Custom-Keycards/wiki/%5B2%5D-Creating-new-Keycard-Door#default-0_defaultlocationjson)

**Comment by RebornOG** [comment]
Thanks got it to work.
